site_name: '许晨杰的个人主页'
site_description: '一名有理想、会思考、能沟通的工程师'
repo_name: 'ChenjieXu/ChenjieXu.github.io'
repo_url: 'https://github.com/ChenjieXu/ChenjieXu.github.io'
nav:
  - 主页: index.md
#  - about_me: about_me.md
  - 新闻报道: news.md
  - 教育经历: education.md
  - 所获荣誉:  honors.md
  - 发表刊物: publications.md
#  - work: work.md
#  - skills: skills.md
#  - models.md
#  - ... | models/*.md
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/favicon.png
  feature:
    tabs: false
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ChenjieXu'
#extra_javascript:
#  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
#  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
#  - javascripts/tables.js
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
plugins:
  - search
  - awesome-pages